# Theme settings
doks:
    baseurl:
    color_theme: blue # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text:
            image: true
        nav:
            - item_name: Use Cases
              item_url: '/use-cases'
            - item_name: Tool Center
              item_url: '/tool-center'
            - item_name: Specification
              item_url: 'https://cyclonedx.org/docs/1.2'
    footer:
        content:
            logo:
                text:
                image: true
            copyright:
        social_list:
            - network_name: twitter
              network_title: Twitter
              profile_url: 'https://twitter.com/CycloneDX_Spec'
            - network_name: github
              network_title: GitHub
              profile_url: 'https://github.com/CycloneDX'
            - network_name: groupsio
              network_title: Groups.io
              profile_url: 'https://groups.io/g/CycloneDX'
            - network_name: slack
              network_title: Slack
              profile_url: 'https://cyclonedx.org/slack/invite'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
